apiVersion: apps/v1
kind: Deployment
metadata:
  name: hubexporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hubexporter
  template:
    metadata:
      labels:
        app: hubexporter
    spec:
      containers:
      - name: hubexporter
        image: docker.io/ihenik/hubexporter:latest
        env:
        - name: API_URL
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: API_URL
        - name: API_TOKEN
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: API_TOKEN
