apiVersion: v1
kind: Service
metadata:
  name: HubExporter-exporter-service
  labels:
    app: HubExporter
spec:
  selector:
    app: HubExporter
  ports:
    - name: metrics
      port: 9000
      targetPort: metrics